### ISSUE TITLE
401 Client Error

### ISSUE THREAD

**Issue by metanovii** [n0madic/gitlab-registry-images-cleaner#13]
when i try connect as gitlab-ci-token:
`INFO     Found 1 repositories
INFO     SCAN repository: some_user/docker-registry-cleaner
DEBUG    Starting new HTTPS connection (1): git.some.domain:443
DEBUG    https://git.some.domain:443 "GET /jwt/auth/?service=container_registry&scope=repository:some_user/docker-registry-cleaner:* HTTP/1.1" 200 1070
DEBUG    Starting new HTTPS connection (1): registry.git.some.domain:443
DEBUG    https://registry.git.some.domain:443 "GET /v2/some_user/docker-registry-cleaner/tags/list HTTP/1.1" 401 176
WARNING  Encountered a HTTP error when trying to access repository some_user/docker-registry-cleaner
401 Client Error: Unauthorized for url: https://registry.git.some.domain/v2/some_user/docker-registry-cleaner/tags/list`

**Comment by n0madic** [comment]
You need a personal access token with `api` scope
https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html
