### ISSUE TITLE
Provide example to run on gitlab.com

### ISSUE THREAD

**Issue by asyd** [n0madic/gitlab-registry-images-cleaner#2]
Hi, 
I'm really interested by this script, but unfortunately I don't find a way to run it on gitlab.com registries. I'm even wonder if it's possible.. have you ever tried that by chance?

**Comment by asyd** [comment]
Ah, it seem to be impossible at this moment, see https://gitlab.com/gitlab-org/gitlab-ce/issues/18392

**Comment by asyd** [comment]
Thanks to @urmet I can get it working by removing fetching the whole catalog. 

I'll try to send you a PR to improve usage

**Comment by n0madic** [comment]
I did so that when you specify repositories, the entire directory should not be loaded
Commit https://github.com/n0madic/gitlab-registry-images-cleaner/commit/1f5ae2e25f9585928b07a8e696a811211c55175d
