### ISSUE TITLE
Tool dependencies

### ISSUE THREAD

**Issue by GRomR1** [n0madic/gitlab-registry-images-cleaner#4]
Please add a `requriments.txt` file for simple solving utility dependencies:
requests
configparser

And write notification that should use python3

**Comment by n0madic** [comment]
https://github.com/n0madic/gitlab-registry-images-cleaner/commit/5e40ed028cf15a9e22e48782b247c893d59945ac

**Comment by n0madic** [comment]
The utility works well in Python 2.7 / 3.5

**Comment by GRomR1** [comment]
Really? Ok, I'm sorry, my mistake.
Thanks for your program but I can't use it.
And I don't know why I can't get a corrent JWT token from my Gitlab instance. Also I was trying to get the token and tags list with cURL and also an unauthorized error was happened.

But I've solved the problem of unused images with [Docker Distribution Pruner](https://gitlab.com/gitlab-org/docker-distribution-pruner).

**Comment by n0madic** [comment]
For JWT to work, you must specify the admin GitLab account

**Comment by n0madic** [comment]
Docker Distribution Pruner is more of a garbage collector
