### ISSUE TITLE
Feature-Request: Use CI_JOB_TOKEN

### ISSUE THREAD

**Issue by svenbs** [n0madic/gitlab-registry-images-cleaner#6]
Hi, 

it would be great if gricleaner could use CI_JOB_TOKEN as authentication token against the registry.

Regards,
Sven

**Comment by n0madic** [comment]
It's not difficult, done https://github.com/n0madic/gitlab-registry-images-cleaner/commit/7e6d4df4cf832f7b0a24ff3ca6e712927deda0a4
But I'm not sure that the token will have enough permissions for all operations...
